### PR TITLE
Task 3

### PR DESCRIPTION
**Pull request by Ivanko5417**
Service is done, all additional tasks are completed ( async/await, es6 modules, webpack, swagger, unit tests, handlers are separated, handled error scenario)

Link to product-service API - https://kgydu5ditk.execute-api.eu-west-1.amazonaws.com/dev/products
Link to front - https://d2n9kz6v2jjh2t.cloudfront.net/

LInk to FE MR - https://github.com/Ivanko5417/nodejs-aws-fe/pull/2

### CODE REVIEW

**Review by valakar — APPROVED** [review]

**Comment by valakar** [comment]
Hi @Ivanko5417 , can you please add usage of Async/Await in lambda functions?

As it was mentioned during online lecture, there should be async call or something similar

**Comment by Ivanko5417** [comment]
Hi @valakar, I've added await in handlers

**Comment by valakar** [comment]
Thanks, btw everything looks great!

**Comment by valakar** [comment]
You can also try to make it to look like real promise by returning not simply data from json, for example by returning new promise with some timeout
(I have already submitted top mark in cross-check)

**Comment by Ivanko5417** [comment]
I think it's not necessary, because the next task will be about connection lambda to the DB and real promises will be there

**Pull request merged**
