### PR TITLE
Task 9

### PR DESCRIPTION
**Pull request by Ivanko5417**
3 - A working and correct express application should be in the bff-service folder. Reviewer can start this application locally with any valid configuration in the .env file and this application should works as described in the task 9.1
5 - The bff-service should be deployed with Elastic Beanstalk. The bff-service call should be redirected to the appropriate service : product-service or CART. The response from the bff-service should be the same as if product-service or CART services were called directly.
+1 - Add a cache at the bff-service level for a request to the getProductsList function of the product-service. The cache should expire in 2 minutes.
+1 - Use NestJS to create bff-service instead of express

Bff url: http://ivanko5417-bff-api-dev.eu-west-1.elasticbeanstalk.com/

### CODE REVIEW

**Comment by candentira** [comment]
@Ivanko5417 could you please provide following links:
- example of the create product API call with all needed information: URL, payload, headers, etc.
- example how to call product-service and CART services via bff-service service URL

**Review by RidgeA — COMMENTED** [review]
7/7

**Review by RidgeA — APPROVED** [review]
7/7

**Comment by Ivanko5417** [comment]
> @Ivanko5417 could you please provide following links:
> 
> * example of the create product API call with all needed information: URL, payload, headers, etc.
> * example how to call product-service and CART services via bff-service service URL

Sorry:
products service through bff GET http://ivanko5417-bff-api-dev.eu-west-1.elasticbeanstalk.com/product
  get all products:GET http://ivanko5417-bff-api-dev.eu-west-1.elasticbeanstalk.com/product/products
  add product: POST http://ivanko5417-bff-api-dev.eu-west-1.elasticbeanstalk.com/product/products
  BODY: { 
    "title": "Audi e-tron",
    "description": "Descr",
    "price": 25999922,
    "count": 2
  }
  
cart service through bff GET http://ivanko5417-bff-api-dev.eu-west-1.elasticbeanstalk.com/cart/profile/cart

**Pull request merged**
